// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package xdp

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type australisBlockEntry struct {
	_        structs.HostLayout
	ExpiryNs uint64
}

type australisConfig struct {
	_            structs.HostLayout
	GamePort     uint16
	Pad          uint16
	SynPerWindow uint32
	WindowNs     uint64
}

type australisSynState struct {
	_             structs.HostLayout
	WindowStartNs uint64
	Count         uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	australisMapAustralisBlocklist = "australis_blocklist"
	australisMapAustralisConfig    = "australis_config"
	australisMapAustralisStats     = "australis_stats"
	australisMapAustralisSyn       = "australis_syn"
	australisProgAustralisFilter   = "australis_filter"
)

// loadAustralis returns the embedded CollectionSpec for australis.
func loadAustralis() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_AustralisBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load australis: %w", err)
	}

	return spec, err
}

// loadAustralisObjects loads australis and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*australisObjects
//	*australisPrograms
//	*australisMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadAustralisObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadAustralis()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// australisSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type australisSpecs struct {
	australisProgramSpecs
	australisMapSpecs
	australisVariableSpecs
}

// australisProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type australisProgramSpecs struct {
	AustralisFilter *ebpf.ProgramSpec `ebpf:"australis_filter"`
}

// australisMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type australisMapSpecs struct {
	AustralisBlocklist *ebpf.MapSpec `ebpf:"australis_blocklist"`
	AustralisConfig    *ebpf.MapSpec `ebpf:"australis_config"`
	AustralisStats     *ebpf.MapSpec `ebpf:"australis_stats"`
	AustralisSyn       *ebpf.MapSpec `ebpf:"australis_syn"`
}

// australisVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type australisVariableSpecs struct {
}

// australisObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadAustralisObjects or ebpf.CollectionSpec.LoadAndAssign.
type australisObjects struct {
	australisPrograms
	australisMaps
	australisVariables
}

func (o *australisObjects) Close() error {
	return _AustralisClose(
		&o.australisPrograms,
		&o.australisMaps,
	)
}

// australisMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadAustralisObjects or ebpf.CollectionSpec.LoadAndAssign.
type australisMaps struct {
	AustralisBlocklist *ebpf.Map `ebpf:"australis_blocklist"`
	AustralisConfig    *ebpf.Map `ebpf:"australis_config"`
	AustralisStats     *ebpf.Map `ebpf:"australis_stats"`
	AustralisSyn       *ebpf.Map `ebpf:"australis_syn"`
}

func (m *australisMaps) Close() error {
	return _AustralisClose(
		m.AustralisBlocklist,
		m.AustralisConfig,
		m.AustralisStats,
		m.AustralisSyn,
	)
}

// australisVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadAustralisObjects or ebpf.CollectionSpec.LoadAndAssign.
type australisVariables struct {
}

// australisPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadAustralisObjects or ebpf.CollectionSpec.LoadAndAssign.
type australisPrograms struct {
	AustralisFilter *ebpf.Program `ebpf:"australis_filter"`
}

func (p *australisPrograms) Close() error {
	return _AustralisClose(
		p.AustralisFilter,
	)
}

func _AustralisClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed australis_bpfel.o
var _AustralisBytes []byte
