//go:build linux

// Package xdp loads the Australis XDP/eBPF filter and manages its maps. Linux
// only. The compiled BPF object is generated by bpf2go (committed, so building
// needs no clang); regenerate with `go generate ./xdp` on a machine with clang.
package xdp

// Regenerate with clang installed (Linux). The -I is the multiarch libc include
// so <asm/types.h> resolves; adjust the arch dir if regenerating on non-amd64.
//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g -Wall -I/usr/include/x86_64-linux-gnu" -target bpfel,bpfeb australis australis_xdp.c

import (
	"fmt"
	"net"
	"os"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/rlimit"
)

// PinnedBlocklistPath is where the loader pins the convicted-IP map so the
// australis-agent (a separate process) can add/remove bans at the NIC.
const PinnedBlocklistPath = "/sys/fs/bpf/australis_blocklist"

const bpffs = "/sys/fs/bpf"

// BlockEntry mirrors `struct block_entry` in australis_xdp.c. Value of the
// blocklist map: absolute expiry in CLOCK_MONOTONIC ns (0 = never expires).
type BlockEntry struct {
	ExpiryNs uint64
}

// xdpConfig mirrors `struct config`.
type xdpConfig struct {
	GamePort     uint16
	_            uint16
	SynPerWindow uint32
	WindowNs     uint64
}

// Options configure the filter at load time.
type Options struct {
	Iface        string
	GamePort     uint16
	SynPerWindow uint32
	Window       time.Duration
}

// Loader owns the loaded objects and the attached XDP link.
type Loader struct {
	objs australisObjects
	lnk  link.Link
}

// Load compiles nothing (the object is embedded), loads it into the kernel, sets
// config, pins the blocklist map, and attaches to the interface.
func Load(opt Options) (*Loader, error) {
	if err := rlimit.RemoveMemlock(); err != nil {
		return nil, fmt.Errorf("remove memlock: %w", err)
	}
	l := &Loader{}
	if err := loadAustralisObjects(&l.objs, nil); err != nil {
		return nil, fmt.Errorf("load bpf objects: %w", err)
	}

	cfg := xdpConfig{
		GamePort:     opt.GamePort,
		SynPerWindow: opt.SynPerWindow,
		WindowNs:     uint64(opt.Window.Nanoseconds()),
	}
	if err := l.objs.AustralisConfig.Update(uint32(0), &cfg, ebpf.UpdateAny); err != nil {
		l.objs.Close()
		return nil, fmt.Errorf("set config: %w", err)
	}

	_ = os.MkdirAll(bpffs, 0o755)
	_ = os.Remove(PinnedBlocklistPath) // clear a stale pin from a previous run
	if err := l.objs.AustralisBlocklist.Pin(PinnedBlocklistPath); err != nil {
		l.objs.Close()
		return nil, fmt.Errorf("pin blocklist at %s: %w", PinnedBlocklistPath, err)
	}

	iface, err := net.InterfaceByName(opt.Iface)
	if err != nil {
		l.teardown()
		return nil, fmt.Errorf("interface %q: %w", opt.Iface, err)
	}
	lnk, err := link.AttachXDP(link.XDPOptions{
		Program:   l.objs.AustralisFilter,
		Interface: iface.Index,
	})
	if err != nil {
		l.teardown()
		return nil, fmt.Errorf("attach XDP to %s: %w", opt.Iface, err)
	}
	l.lnk = lnk
	return l, nil
}

func (l *Loader) teardown() {
	if l.lnk != nil {
		l.lnk.Close()
	}
	_ = l.objs.AustralisBlocklist.Unpin()
	l.objs.Close()
}

// Close detaches the filter and releases all resources (including the pin).
func (l *Loader) Close() error {
	l.teardown()
	return nil
}

// Stats reads the counter array.
func (l *Loader) Stats() map[string]uint64 {
	names := []string{"passed", "dropped_blocklist", "dropped_synflood", "dropped_malformed"}
	out := make(map[string]uint64, len(names))
	for i, n := range names {
		var v uint64
		if err := l.objs.AustralisStats.Lookup(uint32(i), &v); err == nil {
			out[n] = v
		}
	}
	return out
}
